name: Build and push docker image
 
on:
  push:
    branches: ["main"]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
 
      - name: Set up JDK 23
        uses: actions/setup-java@v3.14.1
        with: 
          java-version: 23
          distribution: temurin
 
      - name: Build JAR
        run: mvn clean install -DskipTests
 
      - name: Login to dockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-FoodApp:latest .
 
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-FoodApp:latest
      
        
